### ISSUE TITLE
Do simple guide to install

### ISSUE THREAD

**Issue by SkrudjReal** [NinjasCL/telegraph#2]
I can't compile and run it, i 1-2 days think how to compile this and i can't run it, because an error - 

```
scrooge@god:~/Desktop/telegraph$ ./telegraph https://telegra.ph/Osnovy-kompyuternyh-setej-Tema-8-Protokol-agregirovaniya-kanalov-Etherchannel-10-17
** (UndefinedFunctionError) function Telegraph.init/0 is undefined (module Telegraph is not available)
    Telegraph.init()
    (telegraph 1.0.0) lib/cli/cli.ex:20: Telegraph.CLI.main/1
    (elixir 1.13.0) lib/kernel/cli.ex:126: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

I think, i should download module 'Telegraph' but i don't know how it. Do simple guide how to install this, please :)

**Comment by clsource** [comment]
Thanks for checking this project :)

The installation should be:

1 - Install Elixir (>= v12)
3 - `make deps`
2 - `make build`
3 - Then execute as normal
`./telegraph --path Osnovy-kompyuternyh-setej-Tema-8-Protokol-agregirovaniya-kanalov-Etherchannel-10-17 --json` 

I made a few improvements that will update the lib so you can use the full url instead of just the path.

If you got MacOS heres a preview build

[telegraph.zip](https://github.com/NinjasCL/telegraph/files/8872406/telegraph.zip)

**Comment by clsource** [comment]
https://github.com/NinjasCL/telegraph/releases/tag/v1.0.1

**Comment by SkrudjReal** [comment]
Ohh, thanks! But, i can't compile, maybe i am stupid, but ok ;)

I'll be wait for complete builds for linux
